name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check TypeScript
        run: |
          echo '{
            "compilerOptions": {
              "lib": ["dom", "dom.iterable", "esnext"],
              "target": "esnext",
              "module": "esnext",
              "strict": true,
              "skipLibCheck": true,
              "experimentalDecorators": true
            }
          }' > deno.json
      - run: deno publish 